### ISSUE TITLE
Desktop Helium Wallet GUI Application

### ISSUE THREAD

**Issue by philltran** [dewi-alliance/grants#25]
**Project:**

_Desktop Helium Wallet GUI Application_

**Elevator Pitch:**

Provide a cross platform desktop app for non-cli power users to easily complete Helium wallet transactions on a desktop computer.

**Total fiat/hnt ask:** 

$35,000&nbsp;USD

**Name and Address:**

_KYC info emailed to grants@dewi.org._

**Team**

*Phill Tran*
Discord: @philltran
Github: [https://github.com/philltran](https://github.com/philltran)

*Chris Volkernick*
Discord: @cvolkernick
Website: [IoWE](https://www.internetofwe.net)

**Project Details:**

Provide a cross platform desktop Helium Wallet GUI. This desktop app will provide a means for non-cli power users to complete Helium wallet transactions on a desktop computer.
Project will use Electron framework to compile Windows, Mac and Linux native apps.

MVP features to include:

- Support for a single wallet
- List wallet balance in HNT
- Burn HNT to Data Credits (DC) from this wallet to given payee wallet
- Display list of hotspots associated with wallet
- Transfer a hotspot to another wallet
- Get wallet information using results from cli `info` command
- Send one time payment to one (or more) wallet addresses
- Create a new local wallet from mobile 12 words

Enhanced features may include:

- Stored Repeatable transaction templates
- Commands for validators
- Construct various request (like payment) in a QR code
- Support for multiple wallets
- Address book functionality for payees

**Roadmap:**

| Milestone + Timeframe | Deliverable | Summary | Cost |
| --- | --- | --- | --- |
| MS1,&nbsp;2&nbsp;weeks | Application requirements specification, UX wireframes, UI mockups | Application design and planning including use stories for different user roles, functional and non-functional requirements. The app’s functional requirements are translated into wireframes and then into design mockups | $5,000&nbsp;USD |
| MS2,&nbsp;4&#8209;6&nbsp;weeks | MVP Desktop app | The app's core features are developed into a working cross platform electron applications | $15,000&nbsp;USD |
| MS3,&nbsp;4&#8209;6&nbsp;weeks | Enhanced features | Nice to have features added to MVP application | $15,000&nbsp;USD |

**Comment by JessmFromEarth** [comment]
Hi @philltran can you shoot me a DM on discord JessM#3086 Please

**Comment by JessmFromEarth** [comment]
The DeWi Grant Committee has reviewed this grant application and has moved to close this issue.

Thank you for submitting this application.
