### ISSUE TITLE
Helium Blockchain Python SDK

### ISSUE THREAD

**Issue by ashdwilson** [dewi-alliance/grants#28]
**Project:**

Helium Blockchain Python SDK

**Elevator Pitch:**

One of the first hurdles to integration with any platform is the implementation of basic API interaction patterns. This SDK eliminates the learning curve associated with the minutiae of the Helium blockchain's RESTful API, and bundles performance-preserving service-friendly features like connection pooling and exponential back-off. This SDK abstracts the complexities of API interaction so that developers can rapidly build Python applications for the Helium blockchain.

**Total fiat/hnt ask:** 

1,000 HNT (~$30,000 USD)

**Name and Address:**

Ash Wilson
(Mailing address submitted directly to grants@dewi.org)

**Team or Project website:**

https://ash-wilson.com

**Code Repos of team or key applicants:**

[https://github.com/ashdwilson](https://github.com/ashdwilson)

Relevant projects where the applicant has made substantial contributions:

* CloudPassage platform Python SDK: https://github.com/cloudpassage/cloudpassage-halo-python-sdk
* Kismet Wireless IDS DB and API libraries:
  * https://github.com/kismetwireless/python-kismet-db
  * https://github.com/kismetwireless/python-kismet-rest
* Kalibrate SDR calibration tool wrapper: https://pypi.org/project/kalibrate/
* OpenCellID API wrapper: https://pypi.org/project/opencellid/
* DNS/DANE wrapper for certificate discovery (implements https://datatracker.ietf.org/doc/draft-wilson-dane-pkix-cd/) https://github.com/valimail/dane-discovery

**Project Details:**

Helium Blockchain SDK

* Complete coverage of all Helium blockchain routes described at https://docs.helium.com/api/blockchain/introduction/
* Implement connection pooling and back-off strategy to respond appropriately to API rate limiting.
* Integration testing against Blockchain API, using pytest.
  * Dockerfile for local integration testing
  * Github Actions for CI testing
* CodeClimate for code quality assessment and tracking test coverage.
* Library published in PyPI
* Documentation published via Readthedocs.

This library is offered under the BSD license, and will depend on the following libraries:
* https://pypi.org/project/requests/ (Apache)
* https://pypi.org/project/h3/ (Apache)
* https://pypi.org/project/base58/ (MIT)
* https://github.com/protocolbuffers/protobuf/tree/master/python (BSD)

This library currently exists in beta state at https://github.com/ashdwilson/helium-python

**Roadmap:**

| Milestone + Date | Deliverable | Summary | Cost |
| --- | --- | --- | --- |
| MS1, 2022-02-05 | Blockchain API endpoint coverage | All blockchain API endpoints supported by beta SDK. Community begins integration testing and filing tickets. Beta docs are published and CI process is in place for running integration tests, and tracking code quality and test coverage. | 15,000 USD |
| MS2, 2022-02-15 | Cutoff for filing defect tickets in Github | Cutoff for pre-release bug reports. Triage, prioritization, and fixes begin. | 0 USD |
| MS3, 2022-03-30 | MVP | Bugs addressed, Medium how-to article published, video tutorial for Python REPL ready for publication, documentation is complete, and body of work is ready for transfer to https://github.com/helium organization for ongoing maintenance. | 15,000 USD |

**NOTE**

This has been a work in progress since late November, and funding from DeWi will encourage/enable me to spend the time closing the gap to get this production-ready. 

I'm open to withdrawing this proposal if the submitters of #27 are interested in working together.

**Comment by jthiller** [comment]
Hey Ash, 
I'm mobile this week but just wanted to add a quick note. 
I'm very happy that you submitted this proposal alongside #27. One of the driving factors of doing this all in the open is to bring the best people together on these projects. 
I think the best outcome is that you and the Crypto Balloon team are able to collaborate on one unified library. One library exemplifying best practices for the Helium and Python community will send a better message than two libraries with possibly different approaches. Furthermore, three maintainers are better than two 😉

I welcome you to reach out to the other team (which it looks like you may have already done) to see if you can become a part of their project. I'll be around next week to help facilitate any discussions if necessary. 

In any scenario, I would like to see you be a funded participant of the grants program.

Happy new year!
