### ISSUE TITLE
Enabling Multisig in Helium Libraries

### ISSUE THREAD

**Issue by syuan100** [dewi-alliance/grants#34]
**Elevator Pitch:**
Multisig support for all transactions have been in [blockchain-core](https://github.com/helium/libp2p-crypto/blob/master/src/libp2p_crypto.erl#L660-L679) for a while now. However, there are no easy ways to access the multisig capabilities currently outside of erlang and [rust](https://github.com/helium/helium-crypto-rs/blob/main/src/multisig/mod.rs). By establishing conventions and exposing dev tooling in the [JS](https://github.com/helium/helium-js) for general multisig support, we will enable the developer community to build more secure products that serve the Helium community.

**Value Prop:**
Multisig transactions allow developers to create custodial accounts that enable more secure/decentralized bridging to other chains. By enabling these bridges, it unlocks millions if not hundreds of millions of dollars of liquidity into the ecosystem currently dominated by only a few large, centralized exchanges.

Additionally, multisig opens up an array of possibilities that developers can build novel Helium products with (Example: Multisig addresses can be constructed from ecc_compact keys that miners currently use).

**Total fiat/hnt ask:** 
$10,000 ($20,000 for expedited timeline)

**Name:**
@syuan100 

**Project Deliverables:**
JS Library support for these functions:
- Create multisig public key from other keys
- New multisig signature from multiple public keys / signatures
- Util: Sort public keys
- Util: Sort signatures
- Binary helpers
- Additional helper functions as needed
- Test cases:
    - Create valid multisig address
    - Invalid keys to create multisig address
    - Create valid multisig signature
    - Invalid signatures for multisig signature
    - M of N signatures pass/fail
    - Create multisig payment transaction and pass validation

**Acceptance criteria:**
Code demonstration that creates a multisig address, initiates a transaction to be signed by multisig members, collects signatures to create a multisig signature, and then submits the transaction successfully to the blockchain.

| Milestone + Date | Deliverable | Summary | Cost |
| --- | --- | --- | --- |
| MS1 (March 28 / March 14*) | JS Implementation | Implement project deliverables above in the helium-js lib | 70% |
| MS2 (April 11 / March 21*) | Demonstration | End to end demonstration as outlined in Acceptance Criteria above | 20% |
| MS3 (April 18 / March 28*) | Documentation |  Update helium-js readmes to include documentation for multisig functions | 10% |

_* Expedited timeline dates_

**Comment by syuan100** [comment]
Draft PR to see what library support looks like: https://github.com/helium/helium-js/pull/278

**Comment by syuan100** [comment]
Grant updated to reflect the multisig support already in [helium-crypto-rs](https://github.com/helium/helium-crypto-rs/pull/21)

**Comment by JessmFromEarth** [comment]
Thanks for submitting this steven, I'll shoot you a DM so we can talk further

**Comment by abhay** [comment]
Would love to see the scope of the ask here but this is a slam dunk for me:

- [x] This is necessary tooling for working in the Helium ecosystem
- [x] The grantee with reputation in the Helium community
- [x] The grantee has demonstrable experience writing software in the Helium ecosystem.

My only request is to work with core team members to define the UX around the JS wallet (work with helium-js devs) and Rust wallet (work with rust wallet devs). The rust wallet, in particular, needs some coordination as there is already a 'multisig' component in it around chain variables. 

Also see how we did multisig in the [xorf-generator](https://github.com/helium/xorf-generator). It's a good way to define multisig pub keys in a JSON format.

**Comment by syuan100** [comment]
@JessmFromEarth Updated:
- Added grant amounts (normal timeline vs expedited)
- Slim down scope (kept grant ask to core libs, took out app updates)
- Consolidated milestones

The dates mentioned are if we were to approve and start the grant today (Feb 7). Depending on if this is approved as is, will adjust dates based on when work actually starts.

**Comment by syuan100** [comment]
@JessmFromEarth rescoped this grant for now to be more granular to just implementing JS lib updates.
