### ISSUE TITLE
Evergreen Miner Helium Integration

### ISSUE THREAD

**Issue by evergreendrose** [dewi-alliance/grants#35]
Evergreen Miner
## Elevator Pitch

Your internet is in the hands of a few big players. They own your data, they earn the fees, and at any moment you could lose access. Helium and Chia have made unstoppable, peer owned networks where people own their assets and earn passive income by running a node. Evergreen Miner makes it dead simple to join these unstoppable networks. Earn passive income, store assets, and use Dapps across multiple chains from a single interface. With Evergreen you own your internet without intermediaries. Evergreen has sold $60,000 in product and $2,500 in MRR, and is currently scaling supply to meet new demand.

Total Ask — $87,000

**Website**

[evergreenminer.com](http://evergreenminer.com/)

**Social**

@evergreenminer

@dylanmrose

# Team

*[[Dylan Rose](https://www.linkedin.com/in/dylan-r-1887b5ba/)](https://www.linkedin.com/in/dylan-r-1887b5ba/)* 

6 Years founding wearable HW companies.

Started and built out new initatives at Amazon Ideas, under creator of Google Glass

UW EE Labs Sr Manager of 3 new initatives, customer discovery, and team management of over 20 people. 

*[[Randal Schwartz](https://www.linkedin.com/in/randalschwartz/)](https://www.linkedin.com/in/randalschwartz/)*

4X O’ Reily Published Author for Perl, Educated and trained thousands of developers. 
Google Flutter GDE

35 Years Experience building and scaling software systems

*[[Robi Lin](https://www.linkedin.com/in/robert-lin1/)](https://www.linkedin.com/in/robert-lin1/)*

2 years Consulting at Bain

Former VC at Bloccelerate 

4 years consulting for dozens of Seattle based startups on tech, growth, and ops.

Seeed Studio is manufacturing our devices, and we have several Chia team members and community contributors working on Hard Drive supply, and blockchain engineering.

# Final Deliverables

We will deliver a hybrid mining device that allows users to mine Chia and Helium via HardDrives and a LoRaWAN module plugged into a 40-pin header.

The key objectives are

- HW designs and components that can be scaled
- Supply Chain that is ready for mass consumer adoption
- Software that makes it easy for users to manage their devices
- Software that helps our team manage and improve devices

Today there are some unknowns around the SW piece with helium, we are going to clarify these details in the first phase of the project.

## Software
MVP software was made for the first batch, the next phase is around scaling the MVP
- The primary deliverables are:
    - AWS Management Layer
        - Cognito/GraphQL/IoT
    - ios/android mobile application
        - Using Flutter SDK
    - IoT Management on the Raspberry Pi
        - OTA updates via AWS GreenGrass
        - Various Python and Bash scripts for communication and configuration
        - MQTT/Websocket communication between RPi, Mobile, and AWS
- Registration:
    - Initially, the Pi creates a local network to be discovered by the mobile app
    - The app will inform the Pi of the preferred internet-connected WiFi
    - The Pi will register itself with the AWS IoT services to establish authentication and communicate both over WAN and LAN
    - The User will authorize itself to connect to the registered Device
- Management:
    - The mobile app will use authentication to get authorization for possible actions.
    - Some actions include:
        - Performance of Mining
        - Buying and selling of on-device digital assets
        - Device configuration and runtime
        - Account information

**Please find an expanded project spec [[here](https://www.notion.so/Project-Spec-73ed7ebfba824edca7068240bffb9826)](https://www.notion.so/Project-Spec-73ed7ebfba824edca7068240bffb9826)**

## Designs
![Untitled](https://user-images.githubusercontent.com/86980496/152586078-0f52602b-d42d-4c6d-8033-cecafaad0bec.png)
![Untitled (1)](https://user-images.githubusercontent.com/86980496/152586110-37d480cf-ddf9-4127-80bf-f7060a80ad4d.png)
![Untitled (2)](https://user-images.githubusercontent.com/86980496/152586113-98e112dc-fb6b-47f0-9b97-938e44089678.png)

## Hardware

We have already been shipping and designing hardware for Chia customers.

- We plan to use the a LoRaWAN HAT and are working to find a supplier 
- **update** we are looking into 5G with a few manufactuerers 
    - [https://www.seeedstudio.com/WM1302-Pi-Hat-p-4897.html[](https://store.rakwireless.com/products/rak2245-pi-hat)](https://www.seeedstudio.com/WM1302-Pi-Hat-p-4897.html)
    - [https://store.rakwireless.com/products/rak2245-pi-hat[](https://www.dragino.com/products/lora/item/106-lora-gps-hat.html)](https://store.rakwireless.com/products/rak2245-pi-hat)
    - [https://www.dragino.com/products/lora/item/106-lora-gps-hat.html](https://www.dragino.com/products/lora/item/106-lora-gps-hat.html)

Existing Prototypes, v2 (left) manufactured by Seeed Studio, 25 v1 prototypes up and running made by Dylan Rose
**V1 Review by BrandonCoin https://www.youtube.com/watch?v=F-ugNotzgck**

![Untitled (3)](https://user-images.githubusercontent.com/86980496/152586218-3731718d-0d4e-45ba-8715-ea6f8584606b.png)
![Untitled (7)](https://user-images.githubusercontent.com/86980496/152586579-d2f87acc-a24c-4512-bae3-45624953f932.png)
![Untitled (9) (1)](https://user-images.githubusercontent.com/86980496/152587042-82c445b9-f4f1-415a-a908-5ae76816615d.png)
![Untitled (5)](https://user-images.githubusercontent.com/86980496/152586235-18d70fe3-b3ae-48ea-bd9b-8eebac6176fe.png)

# Benefit to Helium Community
Chia and Helium combined for over 800K nodes in 2021. Both of these protocols are focused on bringing users P2P internet where they can earn and support their communities. A device that bridges the gap and brings Daaps to everyday people will significantly help grow the network and strengthen the community. Chia, and other P2P networks need helium to get away from ISPs and I believe Evergreen will help route applications and assets between peers directly. This first year will give a glimpse at what a peer owned internet really looks like.

# Roadmap
![EVERGREEN Ext (2) (1)](https://user-images.githubusercontent.com/86980496/152586293-fc26e495-ca5f-4173-88eb-7298a063af0a.png)

1. HW Feasibility and Helium SW integration Architecture — **03/15/22**
    1. Source A 40Pin Hat that uses LoWaRan and installs to Raspbian OS
    2. A package for integrating Helium with Current Evergreen Software
    3. 160 Hours @ $120/hr
2. Prototype and test 50 Units made by Seeed Studio | **05/15/22**
    1. First 50 Units created, delivered from Manufacturer
    2. Working Application and firmware
    3. 220 hours @ $120/hr
    4. Prototype expenses $15,000
3. Sell and prepare production for 20,000 units with first 1000 units delivered| **09/15/22**
    1. 1,000 units delivered and operating
    2. 20,000 Unit pre-order
    3. 220 hours @ $120/hr

**Comment by JessmFromEarth** [comment]
@evergreendrose It's great to see you submitted a grant, I'll work with the team to review your grant as soon as we can.

**Comment by hpssjellis** [comment]
@evergreendrose do you have a link to how to make dApps with the EvergreenMiner  and Chia network? Also do you need a miner to develop your dApps? I am just an interested Developer/Teacher?

**Comment by evergreendrose** [comment]
@hpssjellis dropping some links below, early days but the core objects made on CLVM are Chia Asset Tokens (CATs), smart tokens that contain logic. i.e clawbacks, NFT generation, etc.

You do not need a miner to develop dApps, they can be deployed in web or on desktop re offerbin.com or offerpool.io. Also its worth clarifying that our longer term goal is to support dApps on multiple chains. Chia is lower hanging fruit as its linux client is full featured.

Links
https://www.chia.net/2022/01/18/learn-chialisp-with-clovyr.en.html
https://www.chia.net/2021/11/15/the-CATs-out-of-the-bag.en
https://chialisp.com/
https://github.com/Chia-Network/chialisp-web
https://www.businesswire.com/news/home/20220112005414/en/Chia-Launches-the-First-Native-Peer-to-Peer-Exchange-Capabilities-and-DEXs

**Comment by JessmFromEarth** [comment]
The DeWi Grant Committee has reviewed this grant application and has moved to close this issue.

Thank you for submitting this Proposal.
