### ISSUE TITLE
Miner Match

### ISSUE THREAD

**Issue by jcronyn** [dewi-alliance/grants#36]
## Project

**Miner Match**

### Elevator Pitch

Miner Match is a community driven hosting marketplace that allows providers to advertise their hosting agreements and prospective hosts with a place to review their options and eligibility.

### Total fiat/hnt ask

$125,000 HNT

### Name and Address

**Crypto Balloon LLC**

3712 Ringgold Road #185  
Chattanooga, TN 37412

### Team or Project website

https://www.cryptoballoon.net

#### Jennifer Ann Love

- Creator, author of original grant
  - [Original Grant](https://github.com/dewi-alliance/grants/issues/15)

#### Crypto Balloon LLC
- [Github](https://github.com/Crypto-Balloon)

- Engineers

  - **Joe Cronyn**
    - Developer of heliumgrowth.app
    - Maintainer of helium-py
    - [Github](https://github.com/jcronyn)
    - [Gitlab](https://gitlab.com/jcronyn)

  - **Joshua Miller**
    - Developer of heliumgrowth.app
    - Maintainer of helium-py
    - [Github](https://github.com/thecardcheat)
    - [Gitlab](https://gitlab.com/joshuamiller)

  - **Senior Full Stack Engineer**

### Project Details

Miner Match is a community driven hosting marketplace that empowers hotspot hosting providers, both individuals and organizations, to list themselves in an informed competitive marketplace. Prospective hosts can input their available hosting locations to see providers in their area, compare different providers, and easily view hosting eligibility for multiple providers.

Using Helium API location data, the website will allow hosting providers to specify the types of hosts they are looking for and only advertise to those individuals. This simplifies the host-provider search for prospective hosts and provides a centralized marketplace for hosts to search for opportunities.

The base of the platform will be designed as an opensource platform and hosted as a for-profit service long-term. Hosts will be able to search available providers and apply to host for free.

### Long Term Viability

Long term, the Miner Match service expects to provide user and integration-driven value for multiple parties within the Helium ecosystem. Miner Match will seek funding via affiliate marketing and other partnerships. In addition and as required, Miner Match will begin to charge nominal, lead-driven fees to providers for services provided. Miner Match intends to be the source for researching hosting viability and comparing competing offers for the foreseeable future. 

### Roadmap

| Milestone + Date | Deliverable                                                           | Summary                                                                                                                                                                    | Cost       |
|------------------|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| MS1, Q2-2022     | User Experience Design and Signup/Demand Generation.                  | Create UX Mockup that illustrates user adoption flows. Generate 1000+ unique host signups (with location having one or fewer active hotspots) and 500+ provider signups.   | 15,000 USD |
| MS1, Q2-2022     | Provider signup/registration & landing page for hosts (coming soon).  | Create project, initial infrastructure, basic modeling, admin. Build provider signup and registration flows.                                                               | 25,000 USD |
| MS2, Q3-2022     | Basic public search functionality.                                    | Create search client for prospective hosts that returns valid providers based on basic criteria.                                                                           | 25,000 USD |
| MS3, Q3-2022     | Add filters for hosts and providers to improve experience.            | Add filters and search parameters for provider and host experiences.                                                                                                       | 25,000 USD |
| MS4, Q3/Q4-2022  | Full product launch, opensource base release.                         | Search for hosts and tooling for providers completed and released. Base platform opensource project released. Additional infrastructure/overhead for OSS release and SaaS. | 25,000 USD |
| MS4, Q3/Q4-2022  | Full press release - blog posts, video collaborations, social promos. | Alongside and following release, deliver blog posts, videos, promos that outline and highlight the tool and its utility to the community.                                 | 10,000 USD |

**Comment by JessmFromEarth** [comment]
Thank you for resubmitting this grant proposal, we're looking forward to reviewing it with our team.

**Comment by katepmcandrew** [comment]
Hey there! We'd love to talk about this new proposal. Can you please email me at kate@bolt.io to schedule a time? Thanks!
