### ISSUE TITLE
Helium in Space! STEM Education through telemetric rocketry on the The People's Network

### ISSUE THREAD

**Issue by sebastian-king** [dewi-alliance/grants#38]
## Project:
**Helium in Space!**

### Elevator pitch:
Our project is to send a rocket into space (beyond the Karman line) whilst tracking the rocket and receiving real time telemetry information via The People’s Network. What makes this special? It will be one of the first student-built rockets into space, and the project will undertake STEM and community outreach around the US conducted through the University of North Texas and its flagship student engineering organization, UNT Robotics & Aerospace.

The community support and outreach will foster engagement with and increase exposure to The People’s Network, bring people into STEM, and drive Helium into the final frontier.

### Total fiat/hnt ask:
$200,000 USD

### Name and Address:
Sebastian King
https://untrobotics.com

#### Overview
Our proposal is to send a [High-Power Rocket](https://www.nar.org/high-power-rocketry-info/) into space, to an altitude of approximately 350,000 ft. The rocket’s position, speed and altitude will be tracked in real-time using telemetry reported from the rocket down to earth, via The People’s Network.
The telemetry received from the rocket will be used to verify the success of the space shot and help write the rocket and Helium into the history books as the highest ever and one of the first student rockets to break the Karman line.
Two or three special ground stations with range of the rockets flight path will be set up to receive the telemetry by participating STEM teams.

#### Rocketry
The main challenge within this proposal is building a rocket capable of reaching space. This was once the task of nations and now the boundaries are being pushed by students and universities. Reaching the Karman line with a student-built/HPR rocket has been done before, with USC’s Traveler-IV rocket, proving the mission is possible and doable. We have the ideal team, resources, and background to make the mission a success.
Our rocket will be a carbon fiber, solid-fuel (APCP) custom-built launch vehicle. Full rocket details will be determined during the design phase.

#### STEM Education/Engagement
A core part of the project is to get other universities, schools, and the community around Texas involved with the project. A key motto of UNT Robotics is “changing the world, one student at a time”. Our Aerospace Division has established and attracted aerospace engineering in North Texas and this project will continue our soaring flight path. By actively engaging in the STEM community, it helps ensure the project maintains momentum.
We have all of the necessary expertise in-house to complete the project, however, STEM engagement will also bring industry leaders to get involved with the project and further increasing TPN’s reach.

#### Exposure & ROI
We intend for this to be a high profile and public project, backed by the UNT Robotics name and staff. Our previous projects of this nature have gone viral, featured on television, the news, and spread knowledge and experience amongst the community. 
The key return during the project will be the Helium brand awareness as well as exposure to, and experience with, The People’s Network as a tool for scientific and engineering projects by the STEM community. The network is a fantastic tool for ground-based scientific projects, and it is well placed to take on space too, similarly to The Things Network which has already branched out into satellite communications.

### Key Applicants & Organisations:
**Sebastian King**
Sebastian is a professional consultant and engineer for RESPEC, the global leader in energy, infrastructure, geoscience, water, environmental and data engineering. He is one of the original founders of UNT Robotics and has experience working on a huge array of ambitious engineering projects. He holds an FCC Technician Class license and is associated with radio-telecommunications organizations around Texas. 

**Jack Sprague**
Jack is an extremely experienced High-Power rocketeer and engineer, who holds a NAR/Tripoli Level 2 certification and has mentored advanced rocketry teams across the US for several years.

**Gunnery Sergeant Joe Moore**
Joe is a retired Master Explosive Ordnance Disposal Technician with the US Marines. He is an expert on explosives and compounds, and currently leads the Aerospace Division within UNT Robotics and has competed in rocketry competitions with NASA. Joe will be the Chief Engineer on this project, and also holds a NAR Level 1 certification.

**Benjamin Bailey**
Ben is a mechanical engineer with a background in telecommunications. He is an expert on the Helium network and blockchain, and serves as the Safety Officer for UNT Robotics.

**University of North Texas**
UNT is a tier-one research institution located in DFW, Texas, it’s engineering campus is a former missile manufacturing facility and UNT owns the site of the US Army Denton Nike Missile Base & Silos.

**UNT Robotics & Aerospace**
UNT Robotics is an engineering organization at UNT with several high profile and highly successful projects under its belt, including the 2022 NASA USLI Rocketry competition. The organization consists of more than 460 students.

### Roadmap:
| Deliverable + Date | Summary | Cost |
| --- | --- | --- |
| 1) Launch Vehicle Preliminary Design, Q3 2022 | The preliminary design and modelling for the launch vehicle completed and signed off by team mentors and leaders. | 50,000 USD |
| 2) Subscale Vehicle Testing, mid-Q4 2022 | Subscale Launch Vehicle manufactured, a successful test flight conducted, and telemetry and launch analysis completed.  | 30,000 USD |
| 3) Full-scale Critical Design & Telemetry Stations Design, late-Q4 2022 | Final design signed off by team mentors and leaders. Ground station design completed, identified parts and antenna requirements. | 30,000 USD |
| 4) Static Motor Testing, Q1 2023 | Static firing of rocket propulsion system completed to show performance and space readiness. | 30,000 USD |
| 5) Full-scale Manufacturing & Testing, Q2 2023 | Final Launch Vehicle manufactured to agreed specifications. | 40,000 USD |
| 6) Demonstration Flight & Telemetry Stations Demonstration, Q3 2023 | Final Launch Vehicle low-altitude test flight with telemetry and control systems tested. | 20,000 USD |
| 7) Launch Day, Q3 2023 | Go for launch. Spaceport America, NM | |

_All project dates will be re-evaulated at each milestone to account for project timeline changes. Currently manufacturing lead times, launch slot availability, scheduling outreach during COVID peaks, etc. are expected to be factors in timeline decisions._

**Comment by JessmFromEarth** [comment]
Thank you for submitting this grant application we are very much looking forward to reviewing it with our team. 🚀

**Comment by JessmFromEarth** [comment]
The DeWi Grant Committee has reviewed this grant application and has moved to close this issue in response to resubmission at a later date. 

Thank you for submitting this Proposal.
