### ISSUE TITLE
Grant Batch 2

### ISSUE THREAD

**Issue by NetScr1be** [dewi-alliance/grants#4]
We are obviously too late for grant batch one.

I just came across dewi.org and the grant program today.

We started work on assembling the resources to pitch a proposal in the deployment support category.

Is the deadline for batch two proposals already set?

If so, what is it?

If not, when will it be set?

Thank you,

--PB--

**Comment by jamiew** [comment]
Hi, this is generally being organized via the online form mentioned the README and news being shared via Discord. Here is the latest: https://discord.com/channels/404106811252408320/813452716286017557/828635455267930162

![Screen Shot 2021-04-09 at 12-41-55 #dewi-announcements - Discord ](https://user-images.githubusercontent.com/1903/114213439-f900ef00-9930-11eb-8b67-1b3cae74950e.png)

Going to close this but please join Discord and ask questions in #dewi if necessary
