### ISSUE TITLE
Environmental Social Governance (ESG) Data Verification: Methods, Standards, & Scalable Deployment Solutions   

### ISSUE THREAD

**Issue by T0admomo** [dewi-alliance/grants#40]
### **Project:**

The Athena Project: Environmental Social Governance (ESG) Data Verification: Methods, Standards, & Scalable Deployment Solutions   

### **Elevator Pitch:**

This project seeks to develop a decentralized data standardization layer on top of the Helium Network to allow interoperable data sets between IoT devices for environmental monitoring. These standards provide the basis for trustless ESG asset verification, and an entire ecosystem of derived regenerative financial (ReFi) services.

**Total fiat/hnt ask:**

USD $90,000

### **Name and Address:**

Athena LLC: 

- *Timothy Carter, Environmental Data Scientist & Policy Organizer
805 Dahlia St. Denver, CO 80220*
https://www.linkedin.com/in/timothy-carter-2a4a361a9
    
- *Christian Casazza, Strategic Market Solutions 
41 Jackson Ave, Bayville, NY, 11709*
https://www.linkedin.com/in/christiancasazza
    

### **Project Details:**

Environmental Social Governance (ESG) assets are projected to be worth 50 trillion dollars by 2025. The current ESG marketplace is mainly composed of assets backed by nothing more than self-reported figures, with loose, un-standardized reporting regulations. This lack of reporting leaves vast demand for verifying environmental, public health, and governance data that cannot be met in a scalable or cost-effective manner by Web 2 implementations.

Data quality, collection methodology, and interoperability are imperative to create a global environmental data repository. Interoperability is the core advantage that decentralized storage technologies offer, making them far better suited for environmental monitoring than the information silos of their legacy predecessors. 

The process of developing industry standards should be carefully cultivated by a network of industry partners. These standards should be tested, subjected to community review, and iterated upon. On this end, we seek to create a forum of various stakeholders in the ecosystem.

Further, investments in environmental monitoring should pay careful attention to scalability, reproducibility, modular design, and ease of deployment. For this purpose, it is beneficial to  design and deploy multiple solutions in parallel to reduce costs where possible without sacrificing ease of deployment to a significant degree.

### Additional Value to Helium:

We hope to build upon, standardize, and improve the processes developed and deployed by previous and current project participants such as https://github.com/dewi-alliance/grants/issues/13 wherever possible. We hope to aid these projects in creating incentive structures for sustainable business models.

###**Roadmap:**

The long-term goal of this project is to develop a system of standards and methodologies that enable the development of an Environmental Social Governance (ESG) Data Standardization layer. This proposal is broken into 2 phases. All reports will be published for the community throughout the project and aggregated into a learning resource at the end of phase 2.

**Phase 1** is for research, reporting, and coordinating industry participation in a forum to develop the basis for a set of recommended standards and methodologies. Our report will include interviews with various stakeholders, data quality verification methods, and data quality financial incentive models. 

| Milestone  | Summary | Breakdown | Funding Requested |
| ---  | ---  | ---  | ---  |
|  M1 - Infrastructure Testing  & Comparison |  Deploy, Test & Compare Monitoring Solutions for optimal cost, ease of deployment, and reproducibility. | <ul><li>Deploy US902-928 Helium node, Multi-parameter weather sensing, soil sensing, and additional sensor technologies. </li><li>DIY Tutorials for sensor assembly and deployments</li><li>Testing and reporting on recommended deployment solutions</li><li>Wildfire monitoring methodologies report.</li><li>Testing Image Transmission over LoRaWAN</li></ul>   |  20,000 Upfront   |
| M2 - Reporting and Forum   | Conduct Initial Analysis and Develop a public forum concerning environmental data standards and data markets.  |  <ul><li>Market Standards Initial Assessment and Road map</li><li>Market Demand and Financial Assets report</li><li>M1 Tutorial Content and Data Sample</li></ul>   |  10,000 Upon Delivery |
|  M3 - Decentralized Data Storage & p2p File transfer  |  The interoperability of decentralized data storage solutions will be key in building the next generation of environmental monitoring solutions. While the technologies have come a long way, their are still few successful implementations to date, for this reason a deep dive and subsequent reporting into the current state and limitations of decentralized storage and p2p file transfer technologies. The report will provide of overview of several providers, a summary of the providers we have decided to build on and why, and the code repos we will be utilizing.  |   <ul><li>Comparative Assessments of P2p file transfer & Decentralized Storage Technology Solutions </li><li>Identify core limitations to real world implementation </li><li> Recommended Solutions for environmental monitoring and regenerative finance implementations</li><li>Decentralized storage solution road map</li><ul> | 15,000 Upfront |

**Phase 2** is intended to deploy, test, and iterate upon the recommendations developed during Phase 1.  The aim is to develop a durable, scalable, and cost-effective off-grid monitoring solution that meets industry standards, fills an economic niche,  utilizes decentralized storage, and incentivizes data collection. We will do this through testing and comparison of materials and engaging the Helium and scientific community throughout the iterative process.

| Milestone  | Summary | Breakdown | Funding Requested |
| ---  | ---  | ---  | ---  |
|  M1 - Off-Grid Design & Network Extension Solutions |  Research & test solutions to extend network connectivity to previously neglected regions. Develop a methodology for the implementation of our chosen solution  |  <ul><li>Prioritize sourcing environmentally friendly materials</li><li>Develop and stress test for the best configuration of durability, cost, ease of deployment, and ease of use</li><li>Rural and off-grid Internet Connection solutions suitable for full-scale deployment</li><li>Publish Findings and Roadmap</li></ul>  |  20,000 Upfront   |
| M2 - Deployment and Testing  | Publish baseline standards for environmental monitoring of drought/flood probability and any other standards derived from the industry forum.   |  <ul><li>Develop field test</li><li>Publish Proposed testing for community feedback</li><li>Deploy Field Test</li><li>Operate for 1 month</li><li>Publish full report with data and methodologies</li></ul>   |  10,000 Upfront  |
|  M3 - Standards & Methodologies  |   Launch and maintain an iterative field study with the dual goal of materials testing and standards implementation.   |   <ul><li>Establish and publish guidelines for Industry standards with network partners for data interoperability and quality using Helium Network</li><li>Create Educational Website with courses and certification process.</li></ul>  | 10,000 Upon Delivery |

###**Final Product:**

In-depth reporting and educational course material hosted through an educational web application concerning:

- Market Applications & Financial Incentives for ESG data
- Data Standards & Decentralized Data Collection
- Operational Methodologies
    - Potential methods to ensure data integrity
    - Ecosystem Niche Monitoring
- Scalable Deployment Feasibility Report
    - Cost & Performance Assessment of various monitoring solutions
    - Comparative Analysis of Scalable Off-Grid Monitoring Solutions
- DIY Tutorial Series

Deployment and testing of approved monitoring solutions to detect the probability of drought/flood and other wildfire mitigation-related observations.

- No fewer than two alternative  monitoring solution designs
- No fewer than two distinct testing locations
- No less than one-month operation of field study (continuation dependent on results and funding)

Publication of an open-access environmental data asset using decentralized storage solutions. Arweave, IPFS, Ceramic etc. This will provide the foundation for an end-to-end ESG asset verification layer on the open web.

Establishment of a committee of stakeholders around ESG assets on data standards

- Published report on current problems around data standardization with current technologies and processes with contributions from various stakeholders
- Report on potential solutions for updating data standards over time through decentralized community involvement

Examples of organizations to be engaged in the development of standards include. but are not limited to:

[[Toucan Protocol](https://toucan.earth/)](https://toucan.earth/) 
[[Moss Earth](https://moss.earth/)](https://moss.earth/)
[[dClimate](https://www.dclimate.net/)](https://www.dclimate.net/)
[[Arbol](https://www.arbolmarket.com/)](https://www.arbolmarket.com/)
[[Moonjelly Dao](http://moonjelly.io/home)](http://moonjelly.io/home) 
[[United States National Forest Service](https://www.fs.usda.gov/)](https://www.fs.usda.gov/) 
[[Colorado Parks & Wildlife](https://cpw.state.co.us/)](https://cpw.state.co.us/)  
Paraguay National Forest Service 
[[Shamba](https://shamba.link/)](https://shamba.link/)
[[Astrea](https://astraea.earth/)[](https://www.athena.wiki/intro.html)](https://astraea.earth/)

### Next Steps:

After completing both of these phases, we plan to launch a full-scale deployment in Paraguay. The deployment is intended to incentivize land stewardship, protect local agriculture, and combat the eutrophication of freshwater ecosystems in the region of Ybycui National Park. The study will provide a reproducible end-to-end market application and use case for the Helium Network. 

**Team or projects social & websites:** 

[https://athena.wiki/[](https://twitter.com/athenaequity)](https://www.athena.wiki/intro.html) 
[https://twitter.com/athenaequity[](https://www.linkedin.com/company/athena-equity-solutions/?viewAsMember=true)](https://twitter.com/athenaequity) 
[https://www.linkedin.com/company/athena-equity-solutions[](https://github.com/AthenaEquity)](https://www.linkedin.com/company/athena-equity-solutions/?viewAsMember=true)

####**Code Repos of team or key applicants:**

[https://github.com/AthenaEquity[](https://github.com/T0admomo)](https://github.com/AthenaEquity)

[https://github.com/T0admomo[](https://t0admomo.github.io/)](https://github.com/T0admomo)

[https://t0admomo.github.io/](https://t0admomo.github.io)

**Comment by T0admomo** [comment]
Hello All! We received some helpful feedback on our deliverable's and have made some changes to the above issue that are noted here, and where changes were not made responses are noted here. I hope this helps provide some more clarity around our project and please feel free to ask any additional questions you may have.

**P1M1: The deliverable for this milestone is unclear to the team. Could you tighten it up and simplify?**

We made changes to the deliverable to simplify. 
| New Deliverable's | 
| --- | 
| Deploy US902-928 Helium node, Multi-parameter weather sensing, soil sensing, and additional sensor technologies.|
| DIY Tutorials for sensor assembly and deployments|
|Testing and reporting on recommended deployment solutions|
|Wildfire monitoring methodologies report.|
|Testing Image Transmission over LoRaWAN|

**P1M2: The initial analysis and forum should be part of any initial project development, maybe a P1M0. The M1 tutorial and data sample should be a deliverable of P1M1. **
The work for this milestone is intended to be conducted in concert with the P1M1 but will likely depend on the completion of the P1M1 before a full retrospective can be provided. We changed the funding for this phase to retrospective in the hopes that this will reflect our intention to conduct these phases in concert in our proposal. 

**P1M3: What is the deliverable here? A report outlining the possibilities? Can you clarify? **
We added the following summary to clarify that this milestone is primarily about research and reporting.

The interoperability of decentralized data storage solutions will be key in building the next generation of environmental monitoring solutions. While the technologies have come a long way, there are still few successful implementations to date. For this reason a deep dive and subsequent reporting into the current state and limitations of decentralized storage and p2p file transfer technologies is needed. The report will provide of overview of several providers, a summary of the providers we have decided to build on and why, and the code repos we will be utilizing.

**P2M2: It looks like the deliverable for this milestone is a report about monitoring drought / flood probability. Can you clarify how you plan to use sensors to provide a metric of actual drought / flood data and how this might be used to monitor the threat of wildfires at some point in the future? If that's part of your vision. **

(This seemed like a lot to include in the OP but let us know if we should make an edit)
We intend to provide the community with a roadmap to not one but multiple avenues of sustainable environmental monitoring solutions including:

-In general , a combination of metrics including temp, humidity, barometric pressure , wind speed & direction, soil moisture & water capacity in addition to a handful of other metrics worth considering can be used to provide a picture of the probability of flood / drought in a given area. This alone can provide the basis for financial services like parametric insurance, which can in turn be expanded into support for insuring rural farmers against fires when they occur. 

-The specific methods , sensors, and pertinent metrics needed to provide backing for financial services can vary widely from ecosystem to ecosystem, and one topography to another, environmental monitoring solutions require field testing , and we felt it best to develop standards within the regenerative finance ecosystem before committing to a methodology. Eventually, recommended methodologies with these things considered will be submitted to the Helium Community and relevant Academia for review and feedback.

- Regenerative Finance marketplaces have the capacity to provide incentive and funding for a wide range of services from data collection and verification to regenerative action like reforestation, and even facilitate disaster relief and mitigation. The methods used to collect the data needed to back these assets will also require the development of market standards. These types of assets have the can widely in scope, from the Micro ( Carbon Sequestration ) to the Macro (Ecosystem Health), and methodologies will be developed and published for supporting a variety of these.

We hope that these answers helped provide the needed clarity. Please let us know if there are any more questions concerning the project or otherwise :)

**Comment by JessmFromEarth** [comment]
The DeWi Grant Committee has reviewed this grant application and has moved to close this issue.

Thank you for submitting this Proposal.
