### ISSUE TITLE
Hotspot Board: Communication platform for owners

### ISSUE THREAD

**Issue by riobah** [dewi-alliance/grants#45]
**Project:**

Hotspot Board

**Elevator Pitch:**

Many new comers configure their hotspot incorrectly (location, antenna gain, etc), effecting the earnings of the others around. Those effected try to reach to these owners at different mediums, generally ending unsuccessful. This project will create a free and public communication platform in between hotspots owners, to help improving the quality of the network setup by collaborative efforts of all owners.

**Total fiat/hnt ask:** 

38,500 USD 

**Team or Project website:**

https://heliumgeek.com

**Team or projects social:**

https://twitter.com/HeliumGeek

**Code Repos of team or key applicants:**

Developers of the HeliumGeek platform (Discord handles)
* riobah
* yasinkafadar

**Project Details:**

This project aims to overcome the shortcomings of the existing communication solutions as below: 

* Not every hotspot owner is on every community platform, hence we should create alternative ways to reach to the owners. 
    * Hotspot boards are public (until the claimed owner makes it private) on the web, which allows people which are not registered to the platform access the messages
    * Hotspot boards are optimized to be indexed by search engines, to reach more people, aiming the hotspot owner.
* Claiming the ownership of the hotspot should not cost to the users. The cost should not block the users to send / read messages
    * This project aims to validate the ownership by using deeplink authentication with the Helium Wallet app. 
    * Helium Board platform will be integrated with the HeliumGeek mobile apps to be able to validate the ownership using Helium Wallet app authentication.

The system will be integrated with the HeliumGeek platform to
* validate the hotspot ownership using Helium Wallet app authentication
* to expand the reach by sending push notifications to the verified users 

![Helium Board](https://heliumgeek.com/grant/heliumboard/HeliumBoard.png)

Key features will be 
* Free wallet authentication; to claim ownership, to send messages (to prevent abuse)
* Free messaging (both ways)
* SEO optimized web content
* HeliumGeek mobile app integration for push notification on messages

**Roadmap:**

| Milestone + Date | Deliverable | Summary | Cost |
| --- | --- | --- | --- |
| MS1, Apr 2022 | Helium Wallet Deeplink Authentication | "Connect your Helium account" functionality will be added to the HeliumGeek iOS and Android apps | 5,000 USD |
| MS2, Jun 2022 | Infrastructure, CRUD APIs, Mobile Board Screens | Infrastructure and database will be setup, authenticated CRUD APIs will be implemented. HeliumGeek iOS and Android applications will have "Hotspot Board" screens, to allow listing, sending messages. Hotspot owner will be able to delete messages. | 12,500 USD |
| MS3, Jul 2022 | Push Notifications for mobile | Platform will be sending push messages to the users for a) New messages for your claimed hotspots b) New replies to the boards you participated | 5,000 USD |
| MS4, Aug 2022 | Web | Hotspot pages, showing the messages. SEO assistance tasks. Listing pages to link to the hotspot pages, to allow discovery by bots. | 7,500 USD |
| MS5, Sep 2022 | Inbox Capability for Mobile | Unread message indicator, marking unread messages | 3,500 USD |
| MS6, Oct 2022 | Security Measures | Extra measures to ensure safe messaging | 5,000 USD |

**Comment by ClarissaDeWi** [comment]
@riobah thanks for submitting this proposal. 👏 Our team will reach out within the next two weeks. In the meantime, please complete part two of the application: https://forms.gle/UjThkG2S1XTtF9kKA

**Comment by syuan100** [comment]
|  | Quick Rubric |
| -- | -- |
| N/A | **Does this increase network adoption?**<br />*(# of organizations, # of HNT burnt through DC usage/network utilization, # of devices added and active)* |
| ✅ | **Does this increase miner and validator participation?**<br />*(# of active miners/validator, Network coverage %, # of wireless protocols)* |
| ✅ | **Does this increase the spread of HNT and other related tokens?**<br />*(# CEX/DEX listings, $ of liquidity, # of payment transactions, # of unique Helium addresses)*  |
| ❔ | **Does this increase the decentralization of the Helium network?**<br />*(# of community developers, # of non-Helium-org clients/services, Ledger/blockchain distribution)* |
| ✅ | **Does this increase the PR or positive brand recognition for Helium?**<br />*(# press appearances, social engagement, trust in HNT Brand)* |
| ❌ | **Does the scope make sense?**<br />*(Grant definitively funds a public not-for-profit good. Deliverables are finite, discrete, and solves a specific problem)* |

**Initial review: Preliminary Reject**
Grant does not pass the quick rubric. Modifications to the current grant are possible to bring it into an acceptable state. Suggestions are made based on the rubric categories.

<hr/>

Thank you for your submission. After careful review and correspondence, we will reject this proposal as is. However, as per our email correspondence, we are looking forward to an updated proposal that scales the scope differently and includes more open source deliverables and includes increased decentralization benefits.
