### ISSUE TITLE
Helium JS SDK - Multisig Support

### ISSUE THREAD

**Issue by jcronyn** [dewi-alliance/grants#47]
### Elevator Pitch

Multisig support for all transactions have been in blockchain-core for a while now. However, there are no easy ways to access the multisig capabilities currently outside of erlang and rust. By establishing conventions and exposing dev tooling in the JS for general multisig support, we will enable the developer community to build more secure products that serve the Helium community.

### Value Prop

Multisig transactions allow developers to create custodial accounts that enable more secure/decentralized bridging to other chains. By enabling these bridges, it unlocks millions if not hundreds of millions of dollars of liquidity into the ecosystem currently dominated by only a few large, centralized exchanges.

Additionally, multisig opens up an array of possibilities that developers can build novel Helium products with (Example: Multisig addresses can be constructed from ecc_compact keys that miners currently use).

### Total fiat/hnt ask

$16,000

### Name 

- **Joe Cronyn**
  - Developer/Maintainer of helium-py
  - [Github](https://github.com/jcronyn)

### Project Deliverables

JS Library support for these functions:

(Items struck through are completed in https://github.com/helium/helium-js/pull/278, assuming that pull request is approved and merged)

- ~~Create multisig public key from other keys~~
- New multisig signature from multiple public keys / signatures
- ~~Util: Sort public keys~~
- Util: Sort signatures
- Binary helpers
- Additional helper functions as needed
- Test cases:
  - ~~Create valid multisig address~~
  - ~~Invalid keys to create multisig address~~
  - Create valid multisig signature
  - Invalid signatures for multisig signature
  - M of N signatures pass/fail
  - Create multisig payment transaction and pass validation

### Acceptance criteria

Code demonstration that creates a multisig address, initiates a transaction to be signed by multisig members, collects signatures to create a multisig signature, and then submits the transaction successfully to the blockchain.

### Roadmap

| Milestone + Date | 	Deliverable      | 	Summary                                                                  | Cost        |
|------------------|-------------------|---------------------------------------------------------------------------|-------------|
| MS1 - 04/21/22	    | JS Code | 	Implement project deliverables above in the helium-js lib                | 	13,000 USD |
| MS2 - 04/25/22	    | Demonstration     | 	End to end demonstration as outlined in Acceptance Criteria above        | 	2,000 USD  | 
| MS3 - 04/30/22	    | Documentation     | 	Update helium-js readmes to include documentation for multisig functions | 	1,000 USD  |

**Comment by syuan100** [comment]
@jcronyn Can you remove the Multisig Address portions of this grant as that work has already been completed? I modified my old multisig PR and I'm hoping to get that merged soon. See: https://github.com/helium/helium-js/pull/278

Thank you!

**Comment by jcronyn** [comment]
@syuan100 Updated address portions to reflect current pull request and referenced your work in the application.
