### ISSUE TITLE
Rural Expansion for Helium Network Usage 

### ISSUE THREAD

**Issue by sarhinkley09** [dewi-alliance/grants#48]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-6e5d3158-7fff-31ab-7bc1-a9538b97aca5"><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Project:</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Rural Expansion for Helium Network Usage&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Elevator Pitch</span><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">:</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The world runs on Agriculture through food supplies, energy creation, and environmental sustainability but oftentimes technology applications are deployed last for farmers and rural communities. As input costs to manage our food and energy supply continue to increase it is vital that we find ways to add value to farm operations and rural communities in order to maintain production. We propose a Helium based in-field sensing system to add value to commodity corn and soybean crop operations, rural communities, and secure the transfer of farm information for every stakeholder in the supply chain.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Total fiat/hnt ask:</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">$90,000 USD</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Sarah Hinkley- CEO/ Co-Founder</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><a href="mailto:sarah@barnowlds.com" style="text-decoration:none;"><span style="font-size:10pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">sarah@barnowlds.com</span></a></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Sarah is the CEO and Co-Founder of Barn Owl Precision Agriculture, a company providing farmers robotic operations support and artificial intelligence driven analysis to help secure our food supply and implement regenerative farming practices. She has held many different management and leadership roles within the food industry since 2008.Sarah was born in Colorado Springs but lived in Texas for her adolescence. She attended Texas State University where she received a Bachelors in Business Administration and Management and Colorado State University where she received a Masters in Healthcare Administration.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bryan Stafford- CTO/ Co-Founder</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bryan Stafford is the CTO and Co-Founder of Barn Owl Precision Agriculture. Bryan has a passion for systems development and efficiency. His interest in agriculture comes from the restaurant industry where he assisted many operations in POS management, development and operational performance. He made his transition from table-to-farm to assist farmers through data management and robotic operational support.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Evan Kotara- Lead Engineer</span></p><p dir="ltr" style="line-height:1.2;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#1d1c1d;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Evan grew up helping on a central Texas family ranch, and got his Computer Engineering degree from Texas A&amp;M.Evan specializes in embedded Linux, and has worked on ARM MCUs, and The Yocto Project. A strong believer in a sustainable future, he has a passion for developing frontier Ag technology. He enjoys binging progressive music, but can also be found on long e-bike rides, both urban exploring and on the trails.</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Art Sedighi- Lead Engineer&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dr. Sedighi is a Wall Street Technology Executive with over 20 years of experience planning, designing, developing and having end-to-end ownership of large enterprise-wide solutions for the Financial Services Industry world-wide.&nbsp; His work focuses on areas of Cryptography, Security, High Performance Computing and Cloud-native architecture.</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">He was the founder and CTO of a dense-computing systems company, which was acquired by Univa in 2008. He led the engineering team at Noble Markets where he ran product development and engineering for an FX real-time clearing infrastructure based on Blockchain technology.&nbsp; He has designed and implemented trading and exchange platforms for the New York Stock Exchange, NASDAQ and the American Stock Exchange.&nbsp; His focus areas are Financial and Regulatory Technology and its implications and impact on the Global Financial Markets, and behavioral economics vis-a-vis impacts in large shared infrastructures such as Cloud and Blockchain.</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dr. Sedighi received his PhD from Texas Tech University in Systems Engineering, holds a Masters in Bioinformatics from the Johns Hopkins University, and a Masters in Computer Science from Rensselaer Polytechnic Institute.</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;">&nbsp;</p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Project Details:</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Barn Owl Precision Agriculture provides robotic operational support and A.I driven analysis for farmers to help them secure our food supply and rediscover the love for the job.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Barn Owl has developed an in-field sensing system with image recognition, called The Owl Perch, for farmers which allows them real-time access to field and crop information and is used to make earlier decisions in the crop cycle. Specifically, The Owl Perch is used in commodity corn and soybean operations to sense and alert farmers on soil properties, environmental conditions, crop stages, and insect and disease presence which when closely monitored allows for targeted inputs and crop loss prevention through early detection. The Helium network has a large presence and value creation to those users in urban areas throughout the U.S and world; however, availability is lacking in rural areas. This project will add Helium to The Owl Perch to secure data transmission, add value to farm operations, increase availability for potential Helium users in rural areas and start building the infrastructure for future collaboration with Ethereum for improved carbon credit tracking.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The data collected and transmitted from The Owl Perch supports farmers in daily operations as well as predictive analysis for better positioning in the supply chain. As a specific example, Barn Owl will deploy The Owl Perch as a hotspot in a given corn farming region. Additional units without hotspot capabilities are deployed around that hotspot for data collection and then transmission occurs through LoRaWAN to the hotspot. The data packets are sent through the chain to The Barn Owl platform which is then accessed and utilized to make decisions by the farmers, stakeholders in the supply chain, the commodities and carbon markets, consumers, and communities. The Owl Perch further acts as an in-field verification system for farmers looking to implement or quantify climate smart farming practices. With 915 million acres of farmland in the U.S and 90% of those acres divided between corn, soybeans, wheat, cotton, and hay this operational support system, with Helium, in data collection, secure transmission, and verification is going to assist in a more productive agricultural ecosystem worldwide.</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:194px;height:322px;"><img src="https://lh5.googleusercontent.com/ftLIHM4xQe268PXR-zJlfmzQh-JPI3iXyKfBIEQnoNN-tBrdjUxEs6QfcWHrjj27-N-YgRI3GX6Bmb79y6g_r3G7jT3roxUAghy4Ero67FayeRvAQeAlkVb6jyPV68k26gQG8o4v" width="194" height="322" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:283px;height:368px;"><img src="https://lh4.googleusercontent.com/2V2Bd9uAeILF1tzHzNSY1Q9SNito_dWtLhu68vMBtyarKhXrBkf34ty2qjV3bR-5v_iRLC29H4ZskbZWXDkdk_08irBQ3NAaiYlN0_iUp9nab1cbp1KTC_yfLzNySD-oMRlrlSUN" width="481.17711171662125" height="644.7800634078006" style="margin-left:-101.7874659400545px;margin-top:-111.59654943596539px;" /></span></span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;">&nbsp;</p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:293px;height:351px;"><img src="https://lh4.googleusercontent.com/b7ptzJPnaWbT1aouYJSipiznSobpsYug-7HZZKIU2hghwd7469ON4L-Cf7HRfjp-4jihUl5dipTAGwgrYpJ1FLelHGu-r_ck51kmwiyHjHBurCRMLZh2q77q3Md8H0xX3ihUDHsx" width="316.31833910034607" height="422.6222865412446" style="margin-left:0px;margin-top:-71.62228654124458px;" /></span></span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;">&nbsp;</p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;">&nbsp;</p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Immediate Goals</span><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Owl Perch is already developed with initial soil sensors, environmental sensors and image recognition and are deployed in farms throughout Colorado and Kansas. This project will integrate Helium with the current hardware to 1) offset the cost of The Owl Perch for farmers and add value to their operations through mining on the hotspot and 2) increase the integrity, security, and verification of the data being collected from farm activities and crop yields for 3rd party users.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Long-term Goals</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Once The Owl Perch is stable with Helium we will work with Nori, a carbon marketplace, to integrate the Helium and Etherium networks for more precise carbon credit management. This will further add value to the agriculture ecosystem through accurate counting of carbon reducing activities that are being performed on farms.&nbsp;</span></p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;">&nbsp;</p><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;">&nbsp;</p><div dir="ltr" style="margin-left:-30.75pt;" align="left">

Milestone + Date | Deliverable | Summary | Cost
-- | -- | -- | --
Assign a full-time project lead, May 15, 2022 | Onboard the project manager | Integrate the Helium network to The Owl Perch for deployment 40 hours | 15,000 USD
Coordinate Barn Owl and Helium engineer, June 1, 2022 | Start Helium integration | The project lead and Helium engineer will coordinate to start onboarding The Owl Perch 20 hours | Part of milestone 1
Deploy 1 Owl Perch, June 15, 2022 | Data transmission to Helium | Onboard 1 Perch hotspot to Helium for in-field testing 80 hours | 12,000 USD
Update current Owl Perch, July 1, 2022 | Prove in-field functionality for 5 units | Core features implemented on-chain and deployed to HNT testnet for 5 units, 50 hours | 15,000 USD
Regional Communications September 1, 2022 Date | Proof of regional value add for producers and stakeholders | Core features scaled on-chain with multiple Owl Perch in a farm region working together 100 hours | 22,000 USD
Validation October 31, 2022 | MVP | Open-source case-study written and published | 7,000 USD
R&D for Helium and Etherium integration, December 31, 2022 | Developer model for cross-blockchain communication | Project plan for cross-blockchain data tracking specifically related to carbon credit management | 19,000 USD
  |   |   |

**Comment by ClarissaDeWi** [comment]
Hello @sarhinkley09 👋 Thanks for submitting a proposal. Our team is reaching out via email to share next steps.
