### ISSUE TITLE
How to submit grants to this repository?

### ISSUE THREAD

**Issue by hpssjellis** [dewi-alliance/grants#5]
@Scottsigel @jamiew 

Would you prefer us just to alter the template.md and do a PR or make a new sensibly labelled folder for our version of the template?

I don't mind either way, but a positives for putting our grant proposals in it's own folder is that we can upload images and files to support our proposal. 

If we do make a new folder then the template should probably be labelled README.md as it would then show up automatically.

Not a big deal either way as images and files could be linked to from other sites. Can you reply with some confirmation either way.

Jeremy Ellis

**Comment by jamiew** [comment]
@hpssjellis the prior batch of applicants actually used this typeform rather than submitting here: https://dewialliance.medium.com/launching-the-dewi-grant-program-9410310129bf

Typeform link: https://dewi-grants.typeform.com/to/D3wdDC0X

I'd advise submitting there for time being, although I'd love to try using GitHub and do things in the open in the future. cc @Scottsigel @wheresaddie

**Comment by hpssjellis** [comment]
@Scottsigel @wheresaddie @jamiew 

LOL, I thought the future was here as the grant link was closed. Any idea when it opens up?

Typeform link: https://dewi-grants.typeform.com/to/D3wdDC0X

**Comment by jamiew** [comment]
That's great, thanks for putting that together. What do you think of throwing some kind of `yyyy-mm` prefix in front of directory names to help give it a feeling of orderliness? 

I'll check with team as far as officially opening batch 2 up. We are a little short-staffed atm so appreciate your patience

**Comment by hpssjellis** [comment]
@jamiew:

Check it out. 
[https://github.com/hpssjellis/grants/tree/master/2020-05-proposal-arduino-portenta](https://github.com/hpssjellis/grants/tree/master/2020-05-proposal-arduino-portenta) Does look a bit more organized. I am in no rush, when ready I will do a PR or use whatever form you setup.

**Comment by wheresaddie** [comment]
might suggest we define a license area/type for the schematics and/or code bases submitted.
