### ISSUE TITLE
Fraud detection in helium transactions

### ISSUE THREAD

**Issue by com90** [dewi-alliance/grants#51]
**Project**

Fraud detection in helium transactions using machine learning approach

**Elevator Pitch**

Like every crypto currency HNT will be suffering from fraud behaviors in the near future. There are already reports of fraud accounts and devices which undermines the trust to the network and causes unfair income for other network users. This project will use machine learning algorithms to the Helium network transactions to detect fraud behavior and monitor them.

**Total fiat/HNT Ask**

65.000 USD

**Name & Address**

Prof. Dr. Mitat Uysal - https://www.dogus.edu.tr/en/academic-staff/faculty-of-engineering/mitat-uysal
Mustafa Ozan Uysal - https://www.linkedin.com/in/ozanuysal/
Ahmet Faruk Acar - https://www.linkedin.com/in/ahmet-faruk-acar-87b122a1/

Address : Barış Sokak Alya Life Residence No:1 Kat:10 Daire:119 Fikirtepe / Kadıköy İstanbul

**Team or Project Web Site**

Appcent - http://appcent.mobi

Appcent is an award-winning technology company specialized in fin-tech and e-commerce that builds mobile applications across the Turkish and Middle East market for many well recognized brands such as Mavi, xCite, Costa Coffee, Alghanim Industries, Hepsiburada, NetWork, Metro, Unilever. Our R&D department has successfully developed and managed innovative machine learning projects funded by TUBITAK (The Scientific and Technological Research Council of Turkey), as well as self-funded IoT projects. Furthermore, with Appcent Academy, we organize training and young talent programs to transfer our sectoral experience to the ecosystem. Most recently in 2021, we have founded Appcent Design to provide end-to-end technology solutions to our partners.

A team of 3 developers, one project manager and academic consultant will be involved in the project.

**Project Details**

The project will consist of three modules;

Monitoring and data collection module
Fraud detection using machine learning
Analytics and alert dashboard

In the first phase we will analyze transactions on the blockchain and train our model to detect fraud behavior. Fraud behavior can be; money laundering, unfair HNT gain, a transaction which the wallet owner is unaware of or any other fraudulent activity. After that we will try different models and measure the performance of algorithms. A dashboard will help users to identify suspicious transactions and raise alerts if necessary.

**Technical Objectives**

Detection of fraudulent actions in blockchain transactions using ML consists of 4 steps;

Input data
Extract features
Train algorithm
Create model

To detect fraud, a machine learning model first needs to collect data. The model analyzes all the data gathered, segments, and extracts the required features from it. Next, the machine learning model receives training sets that teach it to predict the probability of fraud. Finally, it creates fraud detection machine learning models.

PROCESSING THE DATA

Processing the data is the most important part in ML.

It consist of the following steps:

Evaluation and analysis
Obtaining data files
File format types
Preparation data analysis
Arranging and organizing data
Data Analytical tests
 
FRAUD DETECTION

Recognizing fraud
Data analytical software
Anomalies versus fraud within data
Fraudulent data Inclusions and deletions
 
FEATURE EXTRACTION AND SELECTION

Extraction : Getting useful features from existing data
Selection : Choosing a subset of the original pool of features

FEATURE SELECTION IN THIS PROJECT

In this project, a novel cost-sensitive metaheuristic algorithm called as Migrating Birds Optimization(MBO) is used  for cost effective feature selection.MBO is developed by E.Duman,M.Uysal and A.F.Alkaya.The steps of MBO is given as below:

n = the number of initial solutions (birds) 
k = the number of neighbor solutions to be considered 
x = the number of neighbor solutions to be shared with the next solution 
m = number of tours 
K = iteration limit 

Pseudocode of MBO: 

1. Generate n initial solutions in a random manner and place them on a hypothetical V formation arbitrarily. 
2. i =0 
3. while (i <K) 
4.  for (j=0; j<m; j++)
5.  Try to improve the leading solution by generating and evaluating k neighbors  of it. 
6.  i =i+k 
7.  for each solution sr in the flock (except leader)  
8. Try to improve sr by evaluating (k-x) neighbors of it and x unused best neighbors from the solution in front. 
9. i=i+(k-x) 
10.  end for 
11.  end for 
 
THE MAIN ALGORITHMS USED

After selecting the feature, then we are ready to build a ML classification model since fraud detection is a classification problem.

If we look at the literature the following  algorithms are used for classification;

Neural Networks(NN)
k-Nearest Neighbor(kNN)
Support Vector Machine(SVM)
Decision Tree
Random Forest
AdaBoost

We will try all of them to obtain the best results.

<b id="docs-internal-guid-d98f2ffc-7fff-46fc-943f-aff1bd98fc3f" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-weight: normal;"><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Roadmap</span></p><br><br><div dir="ltr" align="left" style="margin-left: 0pt;">

Milestone + Date | Deliverable | Summary | Cost
-- | -- | -- | --
MS1, Q2-2022 | Model building | Data extraction and analysis. We will read transaction data from blockchain and analyze different behaviors. | 10,000 USD
MS2, Q3/Q4-2022 | Algorithm test results | Software development for algorithms and applying them to the data on the blockchain. | 30,000 USD
MS3, Q1-2023 | Final product to detect fraud behavior with open source code | Separating training and test data. Selected algorithm with the best result will discover fraud behavior on the blockchain. | 25,000 USD

</div><br></b>

**Comment by ClarissaDeWi** [comment]
@com90 Thanks so much for submitting this proposal. 👏 It looks like you still need to complete part 2 of the application. Please complete this simple form (https://forms.gle/a124xJmzeWesPeWj7) to streamline the contract process. This form is the final step in the submission process and a lack of this information will delay the contract.
