### ISSUE TITLE
Environmental Monitoring for Sustainably Linked Parametric Insurance

### ISSUE THREAD

**Issue by ChristianCasazza** [dewi-alliance/grants#53]
Environmental Monitoring: Sustainably Linked Parametric Insurance

Eutrophication of Paraguay’s freshwater lakes and streams, soil erosion, increased wildfires, and deforestation have created a system of compounded ecosystem degradation. Paraguay is a remote and rapidly developing country that generally lacks access to public infrastructure. This makes intelligent land management difficult if not impossible. In regions like Paraguay, low-cost LoRoWAN networks are vital for these types of dense monitoring solutions. 

Dense field monitoring solutions are needed both to verify the impact of regenerative actions meant to prevent wildfire conditions and prevent soil loss. Additionally, early wildfire detection systems rely heavily on field monitoring data due to the serious limitation in remote sensing models for this application. 

**Total Ask:**

$90,000

**Team or Project website**
[http://athena.tech](http://athena.tech/)
[https://www.opades.org.py/](https://www.opades.org.py/)
**Team or projects social:**
https://twitter.com/athenaequity

**The Team**

[Timothy L Carter](https://www.linkedin.com/in/timothy-carter-2a4a361a9/) - CTO - Athena Corp.  - timothy@athena.tech
Timothy Carter Is an Environmental Data Scientist and Campaign Director with nine years of experience in project management and public health policy research. Timothy has successfully operated multiple large-scale field data collection initiatives measuring both human and natural systems. He has three years of experience as Director of Campaign Operations within the Public Interest Network where he has proven his ability to recruit, manage, train, and facilitate large teams of staff and volunteers to meet and exceed strategic goals.

[Christian Casazza](https://www.linkedin.com/in/christiancasazza/) - CBO - Athena Corp. - christian@athena.tech

Christian provided go-to-market strategy and product incubation for fintechs in the blockchain. As the first hire on the underwriting team at the fintech firm Yardline Capital, Christian built out the processes for a $10M+ portfolio nearly from scratch. There, Christian developed proprietary underwriting models based on analyzing metrics from multiple data sources. 

[Thomas Price](https://www.linkedin.com/in/thomas-ryan-price/) - CEO - Avano - hardwoodstablecoin@gmail.com
Thomas Price is a bilingual PHD candidate and founder of [Avano](https://www.youtube.com/watch?v=lqbmqB3unuI). He has over 10 years of experience in environmental studies, sustainable development, climate change and GIS. 

[Kimberly Morrow](https://www.linkedin.com/in/kimberly-rose-morrow/)- Account Exective at Touchpoint(Transitioning to Athena full time)
Kimberly Morrow has over a decade of experience bridging private and public interests for sustainabilty. Kimberly has organized and managed large-scale projects with hundreds of thousands of participants.

Christian Fretes - Co-Founder- [OPADES ](https://www.opades.org.py/)- [Cristhianfretes@gmail.com] The Paraguayan Organization For Conservation And Sustainable Development (OPADES) Was Founded On October 12, 2015. It Is A Non-Profit, Trade Union, Non-Partisan And Pluralist Organization, Which Brings Together Young Professionals In The Environmental Area And Enjoys Full Administrative, Organizational, Financial And Political Autonomy. Its purpose Is: to contribute to the sustainable development Of Paraguay, Promoting Respect For Nature And The Ecological Processes That Sustain Life

Marcos Mareco- Member- OPEDES- Marcos is a member of OPEDES with experience with IoT

[Brian Chami](https://www.linkedin.com/in/brian-chami-14459344/?originalSubdomain=ca)- Project Advisor-Co-Founder of [Agrobotic](https://www.agrobotic.io/) and [Researcher](http://brianchami.com/)
 Dynamic and creative ML/IoT Cloud Solution Architect with over 5 years of experience in research, development, and producing
robust solutions. In previous roles, managed, built, and developed solutions along with teams at fast-paced production-cycle and testing environments.
Patent-pending: IoT/Edge AI (Custom Vision) Cloud Solution Architect solution over a Blockchain network

[Andy Nadler](https://www.linkedin.com/in/andy-nadler-5b082169/) -Project Advisor- Peak Hydromet Solutions-
Agrometeorological consulting, weather network establishment, IoT monitoring, parametric insurance. Andy has spent the past 20 years working with all types of weather equipment. 
[www.peakhydromet.ca](http://www.peakhydromet.ca/)

[John Manoochehri](https://www.linkedin.com/in/jmanooch/) - Project Advisor - [Base2](https://base2.works/) - jm@base2.works
John is the founder of design technology firm Base2 and previously worked as an Industry Officer for the UN.

[Michael Wasyl](https://www.linkedin.com/in/michael-wasyl-7b110322/)- Project Advisor - Co-Founder DeerCreek
Michael has extensive experience with scaling start-up businesses and developing new fintech solutions

[Pelli Wang](https://www.linkedin.com/in/pelliwang/)-Project Advisor - Co-Founder DeerCreek
Pelli has extensive experience investing in early stage start-ups as well as developing new fintech solutions. 

**Project Details:**

Our deployment is coordinated with partners **Colegio Nacional** and a local regenerative action nonprofit OPADES. The data collected will facilitate the underwriting of parametric climate insurance that incorporate sustainably linked objectives. What this means, is the data collected will allow access to drought and flood insurance through informing statistical models with localized climate data. Simultaneously, the information can be used for early wildfire detection by sensing smoke, or for managing active wildfires through an understanding of wind speed and direction. Additionally, the data can be used to monitor regenerative wildfire mitigation practices; such as tree planting and regenerative agricultural practices. 

Our deployment will also serve as an educational opportunity for locals on the processes of utilizing Helium in remote areas that lack access to the internet.

**Deployment**
Athena will use grant funds to facilitate the deployment of soil and atmospheric monitoring sensors in two separate study locations both situated between the protected forest ecosystem and agricultural land areas surrounding Ypycui national park in Paraguay. All of the listed sensors are by Decentlabs and can be found on their website.

**Software**

We will develop a web app for the purpose of configuring the sensors in the field as well as monitoring, aggregating, analyzing, and exporting the field data. The app will include the necessary features to fulfill the needs of HIP-19 for the purpose of configuring a Gateway and End Node on Helium. 

**Hardware**

Total
3 x Off-Grid Helium Miner
2 x [[11 Parameter Weather Station](https://www.decentlab.com/products/eleven-parameter-weather-station-for-lorawan)](https://www.decentlab.com/products/eleven-parameter-weather-station-for-lorawan)
12 x [[Soil Water Capacity](https://www.decentlab.com/products/soil-water-potential-and-temperature-sensor-for-lorawan)](https://www.decentlab.com/products/soil-water-potential-and-temperature-sensor-for-lorawan)  
12 x [[Soil Temp & Moisture Profile](https://www.decentlab.com/products/soil-moisture-and-temperature-profile-for-lorawan)](https://www.decentlab.com/products/soil-moisture-and-temperature-profile-for-lorawan) 

Station Types:
1 - Off Grid Helium Miner & Weather Station
2 - Soil Sensors of Both Types

![Yucubai](https://user-images.githubusercontent.com/99146900/163602079-30a7ffdd-37e5-4717-9bc9-0e98ae20e67d.png)

<html>
<body>

Milestone + Date | Deliverable | Summary | Cost
-- | -- | -- | --
Phase 1 Now - June | Phase 1 Now - April |Successfully Deploy Working Prototypes & Secure Transmission. | 20,000 USD
Phase 2 July- September| Scale both sites to full intended capacity for the initial 30-day testing. | Determine Optimal Sensor Density for The Greater Area of Interest | 40,000 USD
Phase 3 Septemer- December| Develop Software Application & Educational Materials | Coordinate a local lender to underwrite Drought & Flood Insurance. Expand Atmospheric Monitoring  | 30,000 USD

</body>
</html>

More on the applications of dense field monitoring data:
[](https://solve.mit.edu/challenges/the-trinity-challenge/solutions/37162)
https://towardsdatascience.com/disease-informed-neural-networks-aa1f17f598a4
https://www.celent.com/insights/787141144

More on the degradation of the local ecosystem:
](https://drive.google.com/file/d/1GMKU-cfEwua391Vq7D_xbVrko2KT3BwX/view )

**Comment by ChristianCasazza** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeBbC7OOxmjyVU0YR6uJ-SFO_QJWkbZGOtILoyM2IyA2epD0Q/viewform

Hello, we have filled out this form. Is there anything else we can do for our proposal?

**Comment by syuan100** [comment]
| | Quick rubric criteria |
-- | --
| ❌ | Is this application unique and not a use case that has been funded in the past? |
| ❔ | Is this application scalable and can it support significant growth? |
| ❔ | Does this application demonstrate a compelling user experience that could lead to adoption? |
| ❔ | Are there portions of this application that can be open sourced as a public good?* |
| ✅ | Does this application provide an opportunity to educate people about the Helium network?* |
| ❌ | Is there a unique and compelling story that can be told with this application?* |

**Initial review: Reject**

Thank you for your submission, however after careful review this does seem to a replication of proposal #13 .

For IoT application grants, we aim to focus on **unique** applications that bring some form of a public good. However, beyond a unique application, the key differentiator here is that the open source deliverable in this grant is simply the data gathered, which doesn't necessarily garner additional benefits for network usage. Proposal #13 delivers a "research station out-of-the-box" to enable other researchers to adopt the Helium ecosystem, which leads to a greater adoption of network usage. This deliverable is the crux of proposal #13 and one of the primary reasons for funding.

While this doesn't fulfill the criteria for our current grant categories, we are exploring options for projects that would like to try out the network by offering sponsored data credits. This may be a path to move forward. If you are interested please comment below and let us know.
